### PR TITLE
Add back functionality to navigate route

### PR DESCRIPTION
**Pull request by stasiukanya**
Implements #44 

Uses `history.go` as suggested by @ryanflorence in https://github.com/reach/router/issues/44#issuecomment-396368172

### CODE REVIEW

**Comment by enzoferey** [comment]
Any chances this gets merged ? I think this is pretty useful for Gatsby as the `window` object can't be used during build process.

Related to [this issue](https://github.com/gatsbyjs/gatsby/issues/5987).

**Comment by brion-fuller** [comment]
Any update for this PR?

**Comment by peterlaxalt** [comment]
Would love to see this get merged. 🤘

**Comment by icyJoseph** [comment]
Does this implementation re-render the previous tree? https://github.com/reach/router/issues/44#issuecomment-461431314

**Comment by WilhelmErasmus** [comment]
This would be great!

**Comment by bpurtz** [comment]
+1

**Comment by calpa** [comment]
Why not merge this commit?

**Comment by revskill10** [comment]
+1000000

**Comment by crutchcorn** [comment]
Please refrain from adding +1 comments. Adding emoji reacts communicates the same enthusiasm for the work without cluttering the thread

**Comment by tanigaki39** [comment]
+1

**Comment by erasmuswill** [comment]
+100

**Comment by blake-hunsicker** [comment]
+1000

**Comment by lesmo** [comment]
I believe that the ```createMemorySource``` should also implement this expected behavior on the ```history::go``` method. It's currently undefined.

**Comment by erasmuswill** [comment]
+10000

**Comment by Kadrian** [comment]
Coming from Gatsby as well, wondering why it's still not possible to simply `.goBack()`. 

So, what's missing for this PR to get merged?

**Comment by ryanflorence** [comment]
Thanks for your patience.

My hesitation here has been around how suspense and caches are going to work.

If you click "back" do we need to go into the `transitioning` state or can we assume since we're going somewhere we've already visited the cache will be filled already?

This PR assumes the cache will be filled. And I suppose the code already assumes they will be filled if the user clicks back.

Anyway, we may find issues when suspense ships in 2032, and we can figure out what to do then.

(j/k react team I love you suspense is going to be amazing)

**Comment by LouiseReid** [comment]
Should this now be working as its merged to master? I'm using v1.2.1 and passing an int to navigate just attaches it to the end of the url

**Comment by ZeeEssDoubleU** [comment]
I'm having the same issue. 

navigate(-1) just append /-1 to the end of the url

**Comment by erasmuswill** [comment]
When this works I have some production workarounds to rectify xD

**Comment by rickiesmooth** [comment]
this doesn't quit work yet, `to === "/-1"` so it doesn't pass the `typeof to === "number"` check. somewhere it prepends `to` with a slash

**Comment by mckelveygreg** [comment]
I'm also on 1.2.1 and it is just appending a -1.

**Comment by rickiesmooth** [comment]
Yeah so the fix is on the beta release, so just do ‘yarn add @reach/router@next’

**Comment by luistak** [comment]
In some use cases I suggest:

`<Link to="../">Back</Link>`

**Comment by adamthrottleup** [comment]
I am also seeing the issue where navigate(-1) is appending a -1 to the url.

I ran ‘yarn add @reach/router@next’ as suggested by @rickiesmooth but the issues persists. Any fix for this yet?

This is my implementation in Gatsby

import { navigate } from "@reach/router";

const goBack = () => {
navigate(-1);
}

<a onClick={goBack} className="back-link">Back</a>

**Comment by adamthrottleup** [comment]
> I am also seeing the issue where navigate(-1) is appending a -1 to the url.
> 
> I ran ‘yarn add @reach/router@next’ as suggested by @rickiesmooth but the issues persists. Any fix for this yet?
> 
> This is my implementation in Gatsby
> 
> ```
> import { navigate } from "@reach/router";
> 
> const goBack = () => {
> navigate(-1);
> }
> 
> <a onClick={goBack} className="back-link">Back</a>
> ```

FYI I fixed this by updating my project's packages to the latest versions by running
`yarn upgrade`

I'm assuming this worked because I got the latest fix to gatsby mentioned above (gatsby was updated to v2.24.63)

**Pull request merged**
