### PR TITLE
Typescript typings added

### PR DESCRIPTION
**Pull request by pret-a-porter**

### CODE REVIEW

**Comment by blainekasten** [comment]
@pret-a-porter Types are already maintained in DefinitelyTyped, What's the benefit of hosting them here instead? 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/reach__router/index.d.ts

**Comment by pret-a-porter** [comment]
No need to install additional package. Capability to change source code and typings in one time.

**Comment by pret-a-porter** [comment]
@blainekasten What do you think?

**Comment by blainekasten** [comment]
@pret-a-porter Unfortunately I think that unless a codebase is actually written in TS, handling the types is best done through definitely typed. At this point, people expect to look there, and TS-contributors will be able to iterate in that environment quicker than here. 

I would love for you to be one of the prolific contributors and maintainers of the types over there though! If we rewrite this router in TS it'll make sense

**Pull request closed without merging**
