### PR TITLE
fix for query params in insert params

### PR DESCRIPTION
**Pull request by VariableVasasMT**
This change is [Reviewable](https://reviewable.io/reviews/reach/router/311)

For issue
https://github.com/reach/router/issues/267

### CODE REVIEW

**Comment by VariableVasasMT** [comment]
@ryanflorence please review.

**Comment by blainekasten** [comment]
@VariableVasasMT code looks like it makes sense, but can we add some tests to make sure this behavior remains stable?

**Comment by VariableVasasMT** [comment]
> @VariableVasasMT code looks like it makes sense, but can we add some tests to make sure this behavior remains stable?

@blainekasten  Will work on that and push soon.

**Comment by blainekasten** [comment]
Still waiting on unit tests!

**Comment by VariableVasasMT** [comment]
will give you in two days, my bad, sorry for struck in a release.

**Comment by VariableVasasMT** [comment]
@blainekasten  I am extremely sorry for this delay, I added the unit test needed

**Comment by VariableVasasMT** [comment]
@blainekasten please have a look.

**Comment by VariableVasasMT** [comment]
@blainekasten please have a look!

**Comment by VariableVasasMT** [comment]
@blainekasten thank you so much!

**Pull request merged**
