### PR TITLE
bump react version to 16.4.1

### PR DESCRIPTION
**Pull request by tsiq-swyx**
fixes https://github.com/reach/router/issues/27

### CODE REVIEW

**Comment by ryanflorence** [comment]
sweeeeeeeet

**Comment by ryanflorence** [comment]
excellent, thanks!

**Comment by tsiq-swyx** [comment]
thank you for acting so fast - because of that i was able to deploy boring-ssg with no issues at all 🤗

**Comment by shaundillon** [comment]
Hi @ryanflorence - Sorry to post in a closed issue, when is this going to be released?

**Pull request merged**
