### PR TITLE
Fix assertion for URL with special characters in Link comonent

### LINKED ISSUE #320: Active link is not asserted for URL with special characters
I think that here:

https://github.com/reach/router/blob/28a79e7fc3a3487cb3304210dc3501efb8a50eba/src/index.js#L406-L407

`location.pathname` should be instead `decodeURIComponent(location.pathname)`

### PR DESCRIPTION
**Pull request by gunnnnii**
Fixes #320 
This is my first pull request, hope I'm doing this correctly 😅

### CODE REVIEW

**Comment by blainekasten** [comment]
@gunnnnii This looks great! Could you add a test that fails if you were to remove the decodeURI part?

**Comment by gunnnnii** [comment]
@blainekasten I've two questions at this point.
Looking further into this, does it really make sense to use `decodeURIComponent` and then compare the result with `encodedHref`? Shouldn't the comparison be between two URI components with the same encoding? So `encodeURIComponent` should be more appropriate, or simply comparing with `href`.

I've also noticed that the browser automatically encodes the pathname. So when running in the browser, the comparison should work fine if I'm understanding it correctly. However, outside of the browser environment, the in memory history source does not encode the pathname, so there it may fail.

If I'm understanding this correctly I'd think the better solution to this would be to call `encodeURI` inside pushState and replaceState for the in memory history. The location object is then always working with the encoded value and the comparison should work outside of the browser.
 
```js
pushState(state, _, uri) {
    let [pathname, search = ""] = uri.split("?");
    let encodedPathname = encodeURI(pathname)
    index++;
    stack.push({ encodedPathname, search: search.length ? `?${search}` : search });
    states.push(state);
},
replaceState(state, _, uri) {
    let [pathname, search = ""] = uri.split("?");
    let encodedPathname = encodeURI(pathname)
    stack[index] = { encodedPathname, search };
    states[index] = state;
}
// or something along those lines
```
Or I could add a check for whether the window object exists, and encode the pathname accordingly

```js
let pathname = window ? location.pathname : encodeURI(location.pathname)
let isCurrent = pathname === encodedHref;
```

**Comment by blainekasten** [comment]
We just landed #344 I wonder if it helps with anything here.

**Comment by gunnnnii** [comment]
> We just landed #344 I wonder if it helps with anything here.

Doesn't that fix this completely? Sure is a lot simpler and more robust then the stuff I had in mind heh. I think it's safe to close this.

**Comment by blainekasten** [comment]
I'm not certain. I was basically just asking if you think it would. Maybe give it a test in your system to see if the new version fixes your issue. Thanks for the help in all of this!

**Comment by kmudrick** [comment]
I do not think that #344 fixed the same issue here

**Pull request closed without merging**
