### PR TITLE
Crash on old android devices fixed

### PR DESCRIPTION
**Pull request by pret-a-porter**
Sometimes window.location.pathname does not exist. I have fixed that case.

### CODE REVIEW

**Comment by blainekasten** [comment]
Hey @pret-a-porter, do you have any documentation to link to that shows that android doesn't have `location.pathname`? AFAIK, that property is pretty well supported. I'd personally be surprised if a UA didn't have `location.pathname` but instead had a `URL` constructor. This change is relatively small so it's likely safe to take either way, but would love to learn more before we move forward with it.

Also, in order to move forward, we're going to need a unit test to make sure we don't break this later on.

**Comment by pret-a-porter** [comment]
Unfortunately no. That has happened in Android WebView. Chrome version 42. I could not reproduce it, just know it by logs. This fix has solved my problem. Maybe it would be helpful for someone else.

**Comment by blainekasten** [comment]
Cool, did some searching around and saw some support tables that indicated this to be true. I'm not fully certain on this stuff, but it seems like a safe attempt if location.pathname isn't there (rare case).

Happy to accept this if you can add a unit test for it!

**Comment by pret-a-porter** [comment]
@blainekasten unit test has been implemented

**Comment by blainekasten** [comment]
Thanks for this!

**Pull request merged**
