### PR TITLE
Allow React.Fragment inside Router

### PR DESCRIPTION
**Pull request by alexluong**
After opening an issue (#181), it seems like this can be useful not only to me but to others. Any thoughts or feedbacks are appreciated. Thanks!

### CODE REVIEW

**Comment by Lucretius** [comment]
I wonder if, instead of adding an additional function and changing the `React.children.map` behavior, if you could add the recursive step inside the existing `createRoute` function, probably [here](https://github.com/reach/router/pull/184/commits/9f3fabcb27161ebb83f9fb965563399a19496ada#diff-1fdf421c05c1140f6d71444ea2b27638R490) before the props checks begin.  Something like:

```
let createRoute = basepath => element => {
  if (!element) {	 
      return null;
  }
 	 
  if (element.type === React.Fragment) {
     return React.Children.map(element.props.children, createRoute(basepath))
  }

  invariant(...)
```

I have not tried this out so it may not work how I'm expecting.

**Comment by alexluong** [comment]
Thanks for the suggestion @Lucretius. However, in my opinion, I don't think that approach would work because it would result in a nested array situation (`[route, route, [route, route], route]`).

**Comment by Lucretius** [comment]
Good point you are right, we would end up with nested arrays.

This sort of leads me into a deeper question of - do we want this to be an exception *just* for `React.Fragment`  Or do we want to allow other sorts of React Elements to have this property where we recursively look inside of its children for more routes?

I don't see anything wrong with the code as written but I do wonder if we are making a one-off change for something that may be a larger feature here.

**Comment by Ayc0** [comment]
Isn't it easier to add React.Fragment in [this if statement](https://github.com/reach/router/blob/master/src/index.js#L483)?

**Comment by ryanflorence** [comment]
Merged one I saw earlier, but you were first, I'm very sorry :( but thank you for helping me understand the need for it :)

**Pull request closed without merging**
