### PR TITLE
Feat/hash in memory source

### PR DESCRIPTION
**Pull request by ricokahler**
Related to #365 

This adds support for `location.hash` in `createMemoryRouter`.

Let me know what you think!

### CODE REVIEW

**Comment by SimenB** [comment]
In case you're interested, I've added support for close to all fields on location in https://github.com/SimenB/router/commit/29d46685e2cfd9d8548ca3a3587114b75a6542d5

I've hard-coded `origin` there, but it'd be trivial to take that as an optional arg next to the pathname, defaulting to e.g. `http://localhost`. We use that via `patch-package` in our project, so it was just more convenient

---

I'm not gonna PR it as it relies on `new URL` and I dunno if that'd be accepted. This repo isn't really maintained, so I don't have the energy to pursue it getting merged. It's pretty quick and dirty, but it works great for us 🙂

**Comment by blainekasten** [comment]
Looks like we need to add support for hash in the push and replace state functions.

**Comment by blainekasten** [comment]
@SimenB This repo _is maintained_, just in my spare time. Gatsby get's the main focus :) Your commit looks good. I don't love requiring a polyfill on URL though.

**Comment by ricokahler** [comment]
> Looks like we need to add support for hash in the push and replace state functions.

@blainekasten , ah my apologizes. Would you like me to continue working on this (i.e. are you accepting PRs?) or would you want to take the feature over?

**Comment by blainekasten** [comment]
@ricokahler if you could finish it up that would be super great! Make sure to add some tests for the pushState and replaceState too! I'd be happy to accept this

**Comment by blainekasten** [comment]
@ricokahler Hey! I'm curious why you closed this?

**Comment by ricokahler** [comment]
@blainekasten i closed this because i no longer have the bandwidth to make the change and i’m also no longer using this library.

Sorry for the lack of notice and thanks for maintaining it!

**Comment by ricokahler** [comment]
I did leave the issue open if someone else wants to implement

**Pull request closed without merging**
